<?php
		
		global $wpdb;
		$action=$_GET['action'];
		$zone_id=$_GET['zone_id'];
		if($action && $zone_id)
		{
			switch($action)
			{
				case 'delete':
				{
					#deleteing...
					$wpdb->query("DELETE FROM ".ADGURU_ZONES_TABLE." WHERE id=".$zone_id);
					$wpdb->query("DELETE FROM ".ADGURU_LINKS_TABLE." WHERE zone_id=".$zone_id);
					echo '<meta http-equiv="refresh" content="0;URL=?page=adguru_adzones">';
				break;
				}
			}
		}#end of if($action && $zone_id)
		 if(isset($_GET['skey']))
		 {
			$keyword_list=$this->get_keywords_from_string(stripslashes($_GET['skey']));
			if($keyword_list){$search=true;}
		}
		if($search)
		{
			
			$tot_key=count($keyword_list);
			$i=0;
			$condition=" ";
			foreach($keyword_list as $key)
			{
			$i++;
			$condition.="name LIKE '%".esc_sql($key)."%' ";
				if($i!=$tot_key){$condition.=" AND ";}
			}
			
			$SQL="SELECT * FROM ".ADGURU_ZONES_TABLE." WHERE ".$condition." ORDER BY id DESC";
		}
		else #if($search)
		{
		
			$rpp=20; #Record Per page;.
			$npage=1; #current page number
			$offset=0;
			if(isset($_GET['npage'])){$npage=intval($_GET['npage']); $npage=abs($npage);}
			if(!$npage){$npage=1;}
			$offset=($npage-1)*$rpp;
			$total_record= $wpdb->get_var("SELECT COUNT(*) AS total_record FROM ".ADGURU_ZONES_TABLE);
			$SQL=" SELECT * FROM ".ADGURU_ZONES_TABLE." ORDER BY id DESC LIMIT ".$offset." , ".$rpp;
		}#end if($search)
		
		$zones=$wpdb->get_results($SQL, ARRAY_A);
		?>

		<script type="text/javascript">
			jQuery(document).ready(function($) {
				//select input field text on click
				jQuery(".all_camp_table input[type=text]").click(function() {
					jQuery(this).select();
				});		
				
				$( "#zone_code_modal" ).dialog({
				height: 230,
				width: 600,
				modal: true,
				autoOpen: false,
				buttons: {
					Cancel: function() {$( this ).dialog( "close" );}
					}		
				
				});//END DIALOG				
				
			});//end document ready

			function show_zone_code_modal(zoneid , name)
			{
			 
			 var php_code="&lt;?php if(function_exists('adguru_zone')){adguru_zone("+zoneid+");} ?&gt;";
			 var shortcode='[adguru zoneid="'+zoneid+'"]';
			 jQuery("#zone_code_php").html(php_code);
			 jQuery("#zone_code_shortcode").html(shortcode);
			 jQuery( "#zone_code_modal" ).dialog( { title: "Get Code for : "+name });
			 jQuery( "#zone_code_modal" ).dialog( "open" );
			return false;
			}			
		
		</script>
		
		<table width="100%">
		<tr><td  width="40%">&nbsp;
			
		</td>
		<td width="60%" align="right">
			<form action="admin.php" method="get">
			<?php if($search){?><a href="?page=adguru_adzones">Clear Search</a><?php } ?>	
			<input type="hidden" name="page" value="adguru_adzones" />
			<input type="text" name="skey" value="<?php echo stripslashes($_GET['skey'])?>" class="sbox" size="40" /><input type="submit" value="Search" class="button" /></form>			
		</td>
		</tr>
		</table>

		<div id="zone_code_modal" title="Get Code">
			<div id="zone_code_content">
					<strong>PHP CODE</strong><BR />
					<code id="zone_code_php">	</code><BR /><BR />
					<strong>SHORTCODE</strong><BR />
					<code id="zone_code_shortcode"></code>
				<!--content will generated by javascript-->
			</div>			
		</div>
	
	    <style type="text/css">
			.all_camp_table tr:hover{background:#FFFFFF;}
		</style>
					
		<table class="widefat all_camp_table">
			<thead>
				<tr>
					<th  width="">ID</th>
					<th  width="">Name</th>
					<th  width="70">Size</th>
					<th  width="70">Status</th>
					<th  width="190" style="text-align:center;">Controls</th>
				</tr>
			</thead>
				<?php 
				$i=0;
				foreach($zones as $zone){ $i++;?>
				<tr>
					<td><strong><?php echo $zone['id']; ?></strong></td>
					<td><strong><?php echo $zone['name']; ?></strong></td>
					<td><?php echo $zone['width']."x".$zone['height']?></td>
					<td><?php echo ($zone['active'])?'Active':'Deactive'; ?></td>
					
					<td align="center">
					<a class="camp_control_link" href="#" onclick="return show_zone_code_modal(<?php echo $zone['id']; ?>, '<?php echo $zone['name']; ?>')">Get Code</a> | 
					<a class="camp_control_link camp_control_link_red" title="Preview" href="?page=adguru_adzones&tab=2&action=copy&cp_from_id=<?php echo $zone['id'];?>">Copy</a> | 
					<a class="camp_control_link" href="?page=adguru_adzones&tab=2&zid=<?php echo $zone['id']; ?>">Edit</a> | 
					<a class="camp_control_link camp_control_link_red" href="?page=adguru_adzones&tab=1&action=delete&zone_id=<?php echo $zone['id'];?>" onclick="return confirm('Are you sure you want to delete this zone?')">Delete</a>
					</td>
				</tr>
				<?php }?>
		</table>

			<?php if(!count($zones)){?><div style="text-align:center; color:#cc0000; font-weight:normal; margin-top: 5px;"><?php echo ($search)? "No zone containing your search terms were found.":"No existing zone. Please add a new zone." ?></div><?php }?>
			<?php if(!$search){$this->print_page_navi($total_record,$npage,$rpp, "admin.php?page=adguru_adzones&tab=1");} ?>
			
		<br /><br /><br />
		<table class="widefat">
			<thead>
				<tr><th>Usage</th></tr>
			</thead>
			<tr>
				<td>
					To show any zone in your site, go to <a href="widgets.php" target="_blank">widget settings</a> page and add <strong>"adGuru Zone"</strong> widget in your sidebar and choose a zone from the zone list. 
					<br /><strong> OR</strong><br />
					Add following php code anywhere in your site front-end pages. Replace the word <strong>'zone_id'</strong> with the <strong>id</strong> of the zone you want to show<br />
					<code>
						&lt;?php if(function_exists('adguru_zone')){adguru_zone(zone_id);} ?&gt;
					</code><br />
					<strong>Example:</strong><br />
					<code>
						&lt;?php if(function_exists('adguru_zone')){adguru_zone(1);} ?&gt;
					</code>
					<br /><br /><strong> OR</strong><br />
					Use following shortcode in your post content<br />
					<code>
						[adguru zoneid="zone_id"]
					</code><br />
					<strong>Example:</strong><br />	
					<code>
						[adguru zoneid="1"]
					</code>					
					<br /><br /><br />
				</td>
			</tr>
		</table>